-- Create propiedades table matching the user's external schema
CREATE TABLE public.propiedades (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pixel_slug text UNIQUE,
  pixel_codigo text,
  operacion text,
  tipo text,
  titulo text,
  precio numeric,
  moneda text,
  precio_texto text,
  descripcion text,
  direccion text,
  barrio text,
  ciudad text,
  lat numeric,
  lng numeric,
  superficie_total numeric,
  superficie_cubierta numeric,
  ambientes integer,
  dormitorios integer,
  banos integer,
  toilets integer,
  cochera boolean DEFAULT false,
  apto_credito boolean DEFAULT false,
  acepta_mascotas boolean DEFAULT false,
  fotos jsonb DEFAULT '[]'::jsonb,
  estado text,
  destacada boolean DEFAULT false,
  url_original text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_scraped_at timestamptz
);

-- Enable RLS
ALTER TABLE public.propiedades ENABLE ROW LEVEL SECURITY;

-- Public read access (no auth needed to browse properties)
CREATE POLICY "Properties are publicly readable"
  ON public.propiedades
  FOR SELECT
  USING (true);

-- Create indexes for common filter queries
CREATE INDEX idx_propiedades_operacion ON public.propiedades (operacion);
CREATE INDEX idx_propiedades_tipo ON public.propiedades (tipo);
CREATE INDEX idx_propiedades_barrio ON public.propiedades (barrio);
CREATE INDEX idx_propiedades_destacada ON public.propiedades (destacada);
CREATE INDEX idx_propiedades_precio ON public.propiedades (precio);
CREATE INDEX idx_propiedades_dormitorios ON public.propiedades (dormitorios);

-- Timestamp trigger
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER update_propiedades_updated_at
  BEFORE UPDATE ON public.propiedades
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();